export const ROUTES = {
  HOME: '/',
  CHECKOUT: '/checkout',
  CONTACT: '/contact-us',
  TERMS: '/terms',
  PRIVACY: '/privacy',
  FAQ: '/faq',
  FORGET_PASSWORD: '/forget-password',
  CHANGE_PASSWORD: '/account/change-password',
  ACCOUNT: '/account',
  ORDERS: '/account/orders',
  HELP_CENTER: '/account/help-center',
  LOGIN: '/account/login',
  SIGN_UP: '/account/signup',
  SEARCH: '/search',
  PRODUCTS: '/products',
  CATEGORY: '/category',
  WISHLIST: '/account/wishlist',
};
